version: "3.5"

networks:
  pyplate_network:
    external: true

services:
  nicegui:
    image: pyplate
    networks:
      - pyplate_network
    ports:
      - target: 8080
        published: 8080
        mode: host
    volumes: 
      - ./src:/app/src # copy entire app into container
  